import { describe, expect, it } from "vitest";

import type { Bar, IndicatorResult } from "../types/alpaca";
import { aggregateBars } from "./aggregateBars";
import { computeStudy, ema, rsi, sma } from "./chartStudies";
// Generated by pandas_ta 0.4.71b0 -- the library the backend computes the
// same indicators with -- from 80 closes that include a flat stretch.
import fixture from "./chartStudies.fixture.json";

function expectSame(actual: (number | null)[], expected: (number | null)[]) {
  expect(actual.length).toBe(expected.length);
  actual.forEach((v, i) => {
    if (expected[i] == null) expect(v, `index ${i}`).toBeNull();
    else expect(v, `index ${i}`).toBeCloseTo(expected[i]!, 8);
  });
}

describe("the studies match pandas_ta", () => {
  it("EMA 9 and 20", () => {
    expectSame(ema(fixture.closes, 9), fixture.ema9);
    expectSame(ema(fixture.closes, 20), fixture.ema20);
  });

  it("the Bollinger middle, upper and lower bands", () => {
    expectSame(sma(fixture.closes, 20), fixture.sma20);
    expectSame(computeStudy({ type: "bb_upper", length: 20, stdev: 2 }, fixture.closes), fixture.bbUpper);
    expectSame(computeStudy({ type: "bb_lower", length: 20, stdev: 2 }, fixture.closes), fixture.bbLower);
  });

  it("RSI 14", () => {
    expectSame(rsi(fixture.closes, 14), fixture.rsi14);
  });

  it("gives nothing where pandas_ta has too few closes", () => {
    expect(rsi(fixture.closes.slice(0, 14), 14).every((v) => v == null)).toBe(true);
    expect(ema(fixture.closes.slice(0, 8), 9).every((v) => v == null)).toBe(true);
  });
});

// Minute bars from 09:30, closes taken from the fixture.
function minuteBars(n: number): Bar[] {
  const start = Date.UTC(2026, 8, 21, 13, 30);
  return Array.from({ length: n }, (_, i) => {
    const c = fixture.closes[i % fixture.closes.length];
    return { t: new Date(start + i * 60_000).toISOString(), o: c, h: c + 0.5, l: c - 0.5, c, v: 100 };
  });
}

function rsiIndicator(bars: Bar[]): IndicatorResult {
  // What the backend sends for an intraday chart: a value per *minute*.
  return {
    name: "RSI",
    kind: "oscillator",
    series: { "RSI 14": bars.map((b) => ({ t: b.t, value: 50 })) },
    colors: {},
    study: { "RSI 14": { type: "rsi", length: 14 } },
  };
}

describe("aggregateBars with an RSI on a 15m chart", () => {
  it("gives the RSI one point per candle, on the candles' own times", () => {
    const bars = minuteBars(15 * 20);
    const out = aggregateBars(bars, bars.map(() => null), 15, [rsiIndicator(bars)]);
    const points = out.indicators[0].series["RSI 14"] as { t: string; value: number | null }[];

    expect(out.bars).toHaveLength(20);
    expect(points.map((p) => p.t)).toEqual(out.bars.map((b) => b.t));
  });

  it("computes it from the 15m closes, not from the minute values", () => {
    const bars = minuteBars(15 * 20);
    const out = aggregateBars(bars, bars.map(() => null), 15, [rsiIndicator(bars)]);
    const points = out.indicators[0].series["RSI 14"] as { t: string; value: number | null }[];

    expectSame(
      points.map((p) => p.value),
      rsi(out.bars.map((b) => b.c), 14),
    );
  });

  it("an oscillator without a formula is still rebucketed, never left per minute", () => {
    const bars = minuteBars(15 * 4);
    const plain = { ...rsiIndicator(bars), study: undefined };
    const out = aggregateBars(bars, bars.map(() => null), 15, [plain]);
    const points = out.indicators[0].series["RSI 14"] as { t: string; value: number | null }[];

    expect(points).toHaveLength(4);
  });

  it("recomputes on the 1m chart too, so the line follows new bars", () => {
    const bars = minuteBars(40);
    const out = aggregateBars(bars, bars.map(() => null), 1, [rsiIndicator(bars)]);
    const points = out.indicators[0].series["RSI 14"] as { t: string; value: number | null }[];

    expect(points.at(-1)!.value).toBeCloseTo(rsi(bars.map((b) => b.c), 14).at(-1)!, 8);
  });

  it("hands back the caller's array when there is nothing to recompute", () => {
    const bars = minuteBars(10);
    const levels: IndicatorResult[] = [{ name: "Daily Range", kind: "level", series: { High: 1 }, colors: {} }];
    expect(aggregateBars(bars, [], 1, levels).indicators).toBe(levels);
  });
});
