/**
 * The studies an indicator can declare as a formula of the chart's closes
 * (STUDY in backend/app/indicators/loader.py), recomputed here from the
 * candles the intraday chart actually draws. The backend computes them once,
 * from minute bars, when the chart loads -- right for a 1m chart at that
 * moment, but a 5m/15m chart's candles are built client-side and the forming
 * one changes with every trade, so its RSI has to come from those candles.
 *
 * Each function is pandas_ta 0.4.71b0's own formula (no TA-Lib installed),
 * so a line looks the same whichever side computed it; the fixture in
 * chartStudies.test.ts was generated by pandas_ta itself. A value is null
 * wherever pandas_ta gives NaN.
 */

export type StudyType = "ema" | "sma" | "bb_upper" | "bb_lower" | "rsi";

export interface Study {
  type: StudyType;
  length: number;
  /** bb_upper/bb_lower: how many standard deviations out. */
  stdev?: number;
}

type Values = (number | null)[];

/** ta.ema, presma=True: seeded with the mean of the first `length` closes,
 * then alpha = 2 / (length + 1). */
export function ema(closes: number[], length: number): Values {
  const out: Values = closes.map(() => null);
  if (closes.length < length) return out;
  let seed = 0;
  for (let i = 0; i < length; i++) seed += closes[i];
  let prev = seed / length;
  out[length - 1] = prev;
  const alpha = 2 / (length + 1);
  for (let i = length; i < closes.length; i++) {
    prev = alpha * closes[i] + (1 - alpha) * prev;
    out[i] = prev;
  }
  return out;
}

/** ta.sma: the plain mean of the last `length` closes. */
export function sma(closes: number[], length: number): Values {
  const out: Values = closes.map(() => null);
  for (let i = length - 1; i < closes.length; i++) {
    let sum = 0;
    for (let j = i - length + 1; j <= i; j++) sum += closes[j];
    out[i] = sum / length;
  }
  return out;
}

/** ta.bbands' deviation: the *sample* standard deviation (ddof = 1) of the
 * last `length` closes. */
function rollingStdev(closes: number[], length: number): Values {
  const out: Values = closes.map(() => null);
  if (length < 2) return out;
  for (let i = length - 1; i < closes.length; i++) {
    let sum = 0;
    for (let j = i - length + 1; j <= i; j++) sum += closes[j];
    const mean = sum / length;
    let squares = 0;
    for (let j = i - length + 1; j <= i; j++) squares += (closes[j] - mean) ** 2;
    out[i] = Math.sqrt(squares / (length - 1));
  }
  return out;
}

/** ta.rsi with its default "rma" smoothing: Wilder's average (alpha =
 * 1 / length, no warm-up window) of the gains and of the losses, from the
 * second bar on. Needs one more close than `length`, as pandas_ta does. */
export function rsi(closes: number[], length: number): Values {
  const out: Values = closes.map(() => null);
  if (closes.length <= length) return out;
  const alpha = 1 / length;
  let gain = 0;
  let loss = 0;
  for (let i = 1; i < closes.length; i++) {
    const change = closes[i] - closes[i - 1];
    const up = change > 0 ? change : 0;
    const down = change < 0 ? -change : 0;
    if (i === 1) {
      gain = up;
      loss = down;
    } else {
      gain = alpha * up + (1 - alpha) * gain;
      loss = alpha * down + (1 - alpha) * loss;
    }
    // 0 / 0 on a flat start, which pandas_ta leaves as NaN.
    out[i] = gain + loss === 0 ? null : (100 * gain) / (gain + loss);
  }
  return out;
}

export function computeStudy(study: Study, closes: number[]): Values {
  switch (study.type) {
    case "ema":
      return ema(closes, study.length);
    case "sma":
      return sma(closes, study.length);
    case "rsi":
      return rsi(closes, study.length);
    case "bb_upper":
    case "bb_lower": {
      const mid = sma(closes, study.length);
      const sd = rollingStdev(closes, study.length);
      const k = (study.stdev ?? 2) * (study.type === "bb_upper" ? 1 : -1);
      return mid.map((m, i) => (m == null || sd[i] == null ? null : m + k * sd[i]!));
    }
  }
}
